Efcore/Mvc/Models/ErrorViewModel.cs
using System;

namespace Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Efcore/Mvc/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Dados;
using Dominio.Entidades;
using Microsoft.AspNetCore.Identity.UI.Pages.Internal.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Scaffolding;
using Microsoft.Extensions.Logging;

namespace Mvc.Controllers
{ 
    public class CategoriaController : Controller
    {

           private readonly ApplicationDbContext _context;

    public CategoriaController(ApplicationDbContext context)
     {
       _context = context;
    }

     [HttpGet]
        public IActionResult Index() 
        {

            var categorias = _context.Categorias.ToList();

            return View(categorias);
        }

        public IActionResult Editar(int id) 
        {
             var categoria = _context.Categorias.First(c => c.Id == id);
            return View("Salvar", categoria);
        }
        public async Task<IActionResult> Deletar(int id) 
        {
             var categoria = _context.Categorias.First(c => c.Id == id);
             _context.Categorias.Remove(categoria);
             await _context.SaveChangesAsync();

             return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Salvar() {

            return View();
        }

    [HttpPost]
          public async Task<IActionResult> Salvar(Categoria modelo) {

            if(modelo.Id == 0) 
            _context.Categorias.Add(modelo);
            else{
                var categoriaSalva = _context.Categorias.First(c => c.Id == modelo.Id);
                categoriaSalva.Nome = modelo.Nome;
                categoriaSalva.PermiteEstoque = modelo.PermiteEstoque;
            }            
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Efcore/Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Mvc.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Efcore/Mvc/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Dados;
using Dominio.Entidades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace Mvc.Controllers
{

    //https://github.com/StphanyBatista/EntityFrameworkCurso
      public class ProdutoController : Controller
    {  

         private readonly ApplicationDbContext _context;

         public ProdutoController(ApplicationDbContext context)
         {
            _context = context;
         } 

         public IActionResult Index() {

            var queryDeProduto = _context.Produtos.Where(p => p.Ativo && p.Categoria.PermiteEstoque).OrderBy(p => p.Nome);

            if(!queryDeProduto.Any())
            return View(new List<Produto>());

            return View(queryDeProduto.ToList());
         }

        [HttpGet]
        public IActionResult Salvar() 
        {
            ViewBag.Categorias = _context.Categorias.ToList();
            return View();
        }

          public IActionResult Editar(int id) 
        {
             var produto = _context.Produtos.First(c => c.Id == id);
            return View("Salvar", produto);
        }

         public async Task<IActionResult> Deletar(int id) 
        {
             var produto = _context.Produtos.First(c => c.Id == id);
             _context.Produtos.Remove(produto);
             await _context.SaveChangesAsync();

             return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Salvar(Produto modelo)
        {
            
            _context.Produtos.Add(modelo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }      
    }
}

Efcore/Mvc/Views/Categoria/Index.cshtml
 @model IEnumerable<Dominio.Entidades.Categoria>

    <h2>Todas Categorias</h2>

    <a href="/Categoria/Salvar" class="btn">Nova Categoria</a>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Nome</td>
                            <td>
                                <a href="/Categoria/Editar/@item.Id" class="btn">Editar</a>
                            </td>
                            <td>
                                <a href="/Categoria/Deletar/@item.Id" class="btn">Deletar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

Efcore/Mvc/Views/Categoria/Salvar.cshtml
@model Dominio.Entidades.Categoria

<h2>Formulário de Categoria</h2>

<form class="form-horizontal" asp-action="Salvar" asp-controller="Categoria" method="POST">

    <input type="hidden" class="form-control" asp-for="Id">
    <div class="form-group">
        <label class="col-md-1 control-label" for="Name">Nome</label>
        <div class="col-md-2">
        <input type="text" class="form-control" asp-for="Nome">
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-1 control-label" for="Name">Estoque</label>
        <div class="col-md-2">
        <input type="checkbox" asp-for="PermiteEstoque">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            <button class="btn btn-success">Salvar</button>
        </div>
    </div>

</form>

Efcore/Mvc/Views/Produto/Index.cshtml
 @model IEnumerable<Dominio.Entidades.Produto>

    <h2>Todos Produtos</h2>

    <a href="/Produto/Salvar" class="btn">Nova Produto</a>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Nome</td>
                            <td>@item.Categoria.Nome</td>
                            <td>
                                <a href="/Produto/Editar/@item.Id" class="btn">Editar</a>
                            </td>
                            <td>
                                <a href="/Produto/Deletar/@item.Id" class="btn">Deletar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

Efcore/Mvc/Views/Produto/Salvar.cshtml
@model Dominio.Entidades.Produto

<h2>Formulário de Produto</h2>

<form class="form-horizontal" asp-action="Salvar" asp-controller="Produto" method="POST">

    <input type="hidden" class="form-control" asp-for="Id">
    <div class="form-group">
        <label class="col-md-1 control-label" for="Name">Nome</label>
        <div class="col-md-2">
            <input type="text" class="form-control" asp-for="Nome">
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-1 control-label" for="Name">Categoria</label>
        <div class="col-md-2">
            <select class="form-control" asp-for="CategoriaId" 
                asp-items='@(new SelectList(@ViewBag.Categorias, "Id", "Nome"))'>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-1 control-label" for="Name">Ativo</label>
        <div class="col-md-2">
            <input type="checkbox" asp-for="Ativo">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            <button class="btn btn-success">Salvar</button>
        </div>
    </div>

</form>

Efcore/Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Mvc</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2024 - Mvc</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>